### ISSUE TITLE
Add support for .net 8

### ISSUE THREAD

**Issue by AnderssonPeter** [xt0rted/dotnet-run-script#258]
Hi in my azure pipeline I currently have to install both .net 8 and .net 6 if you could add .net 8 support them I would speed up my pipelines.

If you can point me in the right direction I can submit a pr.

**Comment by xt0rted** [comment]
v0.6.0 was released earlier with .net 8 support.

**Comment by AnderssonPeter** [comment]
Works like a charm, thanks for the fix!!!
